openapi: 3.0.4
info:
  title: Tor Node Detector
  description: >-
    Tor Detect is an API that checks whether a given IP address belongs to a
    known Tor exit node. Useful for security, access control, and analytics.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/tordetect:
    get:
      summary: Check IP Against Tor Exit Node List
      description: >-
        Tor Detect is an API that checks whether a given IP address belongs to a
        known Tor exit node. Useful for security, access control, and analytics.
      operationId: tordetect
      parameters:
        - name: ip
          in: query
          schema:
            type: string
          required: true
          description: The IP address to check against the Tor exit node list
          example: 185.189.183.143
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  ipAddress: 185.189.183.143
                  isTor: true
                  ipDetails:
                    range:
                      - 3116217344
                      - 3116218367
                    country: NL
                    region: ZH
                    timezone: Europe/Amsterdam
                  parsed: true
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
